# Generated by Django 5.2.1 on 2025-05-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
