# Generated by Django 5.2.1 on 2025-05-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_project_project_name_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'ongoing'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
