# Generated by Django 5.2.1 on 2025-05-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
